version: "3"
services:
  strapi:
    container_name: strapi
    build: .
    image: mystrapiapp:latest
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: strapiDB
      DATABASE_PORT: 5432
      DATABASE_NAME: postgres
      DATABASE_USERNAME: RSJ
      DATABASE_PASSWORD: rsj
      JWT_SECRET: B7XnuJ+yaK7AWYgYKgS9KQ
      ADMIN_JWT_SECRET: B7XnuJ+yaK7AWYgYKgS9KQ
    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./package.json:/opt/package.json
      - ./yarn.lock:/opt/yarn.lock
      - ./.env:/opt/app/.env
      - ./public/uploads:/opt/app/public/uploads
    ports:
      - "1337:1337"
    networks:
      - strapi
    depends_on:
      - strapiDB

  strapiDB:
    container_name: strapiDB
    platform: linux/amd64
    restart: unless-stopped
    env_file: .env
    image: postgres:12.0-alpine
    environment:
      POSTGRES_USER: RSJ
      POSTGRES_PASSWORD: rsj
      POSTGRES_DB: postgres
    volumes:
      - strapi-data:/var/lib/postgresql/data/

    ports:
      - "5432:5432"
    networks:
      - strapi

volumes:
  strapi-data:

networks:
  strapi:
    name: Strapi
    driver: bridge
